//app.js


firstNames = [
  'ALBERT', 
  'ALFRED',
  'ALLEN',
  'ALVIN',
  'ANDREW',
  'ANTHONY',
  'ARNOLD',
  'ARTHUR',
  'BENJAMIN',
  'BERNARD',
  'BILL',
  'BOB',
  'CALVIN',
  'CARL', 
  'CECIL', 
  'CHARLES',
  'CHARLIE',
  'CHESTER',
  'CLARENCE',
  'CLIFFORD',
  'CLYDE',
  'DALE', 
  'DANIEL',
  'DAVID',
  'DONALD',
  'EARL',
  'EDGAR',
  'EDWARD',
  'EDWIN',
  'ELMER',
  'ERNEST',
  'EUGENE',
  'FLOYD',
  'FRANCIS',
  'FRANK',
  'FRED',
  'FREDERICK',
  'GEORGE',
  'GERALD',
  'GILBERT',
  'GLENN',
  'GORDON',
  'HAROLD',
  'HARRY',
  'HARVEY',
  'HENRY',
  'HERBERT',
  'HERMAN',
  'HOMER',
  'HOWARD',
  'JACK',
  'JAMES',
  'JESSE',
  'JOE',
  'JOHN',
  'JOSEPH',
  'KENNETH',
  'LAWRENCE',
  'LEE',
  'LEO',
  'LEON',
  'LEONARD',
  'LEROY',
  'LESTER',
  'LEWIS',
  'LLOYD',
  'LOUIS',
  'MARTIN',
  'MARVIN',
  'MELVIN',
  'MICHAEL',
  'MILTON',
  'NORMAN',
  'OSCAR',
  'PAUL',
  'PETER',
  'PHILIP',
  'RALPH',
  'RAY',
  'RAYMOND',
  'RICHARD',
  'ROBERT',
  'ROGER',
  'RONALD',
  'ROY',
  'RUSSELL',
  'SAM',
  'SAMUEL',
  'STANLEY',
  'THEODORE',
  'THOMAS',
  'VERNON',
  'VICTOR',
  'VINCENT', 
  'WALLACE',
  'WALTER',
  'WARREN',
  'WAYNE',
  'WILLARD',
  'WILLIAM'
] // 100 total

lastNames = [
  "ADAMS", 
  'ALLEN',
  'ANDERSON',
  'BAILEY',
  'BAKER',
  'BARNES',
  'BELL',
  'BENNETT',
  'BOYD',
  'BROOKS',
  'BROWN',
  'BRYANT',
  'BUTLER',
  'CAMPBELL', 
  'CARPENTER', 
  'CARTER',
  'CLARK',
  'COLEMAN',
  'COLLINS',
  'COOK',
  'COOPER',
  'COX', 
  'DAVIS',
  'DIXON',
  'DONALDSON',
  'EDWARDS',
  'ELLIS',
  'EVANS',
  'FOSTER',
  'GARCIA',
  'GRAY',
  'GREEN',
  'GRIFFIN',
  'HALL',
  'HARRIS',
  'HAYES',
  'HILL',
  'HOWARD',
  'HUDSON',
  'HUGHES',
   'HUNTER',
   'JACKSON',
   'JAMES',
   'JENKINS',
   'JOHNSON',
   'JONES',
   'KELLY',
   'KENNEDY',
   'KERESEY',
   'LEE',
   'LEWIS',
   'LONG',
   'MARTIN',
   'MASON',
   'MILLER',
   'MITCHELL',
   'MOORE',
   'MORGAN',
   'MORETTI',
   'MURPHY',
   'NELSON',
   'PARKER',
   'PALMER',
   'PATTERSON',
   'PERRY',
   'PETERSON',
   'PHILLIPS',
   'PIERCE',
   'PORTER',
   'POWELL',
   'PRICE',
   'REED',
   'RICHARDSON',
   'ROBERTS',
   'ROBINSON',
   'ROSS',
   'ROGERS',
   'RODRIGUEZ',
   'SMITH',
   'RUSSO',
   'SANDERS',
   'SCOTT',
   'SIMMONS',
   'SPENCER',
   'STEVENS',
   'STEWART',
   'TAYLOR',
   'THOMAS',
   'THOMPSON',
   'TURNER',
   'WALKER',
   'WARD',
   'WASHINGTON',
   'WATSON', 
   'WHITE',
   'WILLIAMS',
   'WILSON',
   'WOOD',
   'WRIGHT',
   'YOUNG',  
] // 100 total

crewmanTitle = [  // there are twelve crewman
  "Commanding officer",
  "Executive officer ",
  "Bow gunner        ",
  "Bow ammo loader   ",
  "AA gunner 1       ",
  "AA gunner 2       ",
  "Stern gunner      ",
  "Stern ammo loader ",
  "Torpedo mate 1    ",
  "Torpedo mate 2    ",
  "Radio operator    ",
  "Engineer          "
] 

fullName = []


const divOneEl = document.querySelector("#col-one");

const divTwoEl = document.querySelector("#col-two");

// to generate a # between 0 and 99
// Math.floor( Math.random() * 100 );

function randZeroToNinetyNine() {
 return Math.floor( Math.random() * 100 );
}


crewmanTitle.forEach( title=> {
  const newContent = document.createElement('p');
  newContent.classList.add( 'mb-4' )
  newContent.innerText = title
  divOneEl.appendChild(newContent);
})


crewmanTitle.forEach( title=>
    fullName.push( firstNames[ randZeroToNinetyNine() ] + ' ' + lastNames[ randZeroToNinetyNine() ] )
  )

//console.log(fullName)

fullName.forEach( name=> {
  const newContent = document.createElement('p');
  newContent.classList.add( 'mb-4' )
  newContent.innerText = name
  divTwoEl.appendChild(newContent);
})

// divTwoEl.innerHTML = fullName.join('')

// first_names = {
//   1:'ALBERT', 
//   2: 'ALFRED',
//   3: 'ALLEN',
//   4: 'ALVIN',
//   5: 'ANDREW',
//   6: 'ANTHONY',
//   7: 'ARNOLD',
//   8: 'ARTHUR',
//   9: 'BENJAMIN',
//   10: 'BERNARD',
//   11: 'BILL',
//   12: 'BOB',
//   13: 'CALVIN',
//   14: 'CARL', 
//   15: 'CECIL', 
//   16: 'CHARLES',
//   17: 'CHARLIE',
//   18: 'CHESTER',
//   19: 'CLARENCE',
//   20: 'CLIFFORD',
//   21: 'CLYDE',
//   22: 'DALE', 
//   23: 'DANIEL',
//   24: 'DAVID',
//   25: 'DONALD',
//   26: 'EARL',
//   27: 'EDGAR',
//   28: 'EDWARD',
//   29: 'EDWIN',
//   30: 'ELMER',
//   31: 'ERNEST',
//   32: 'EUGENE',
//   33: 'FLOYD',
//   34: 'FRANCIS',
//   35: 'FRANK',
//   36: 'FRED',
//   37: 'FREDERICK',
//   38: 'GEORGE',
//   39: 'GERALD',
//   40: 'GILBERT',
//   41: 'GLENN',
//   42: 'GORDON',
//   43: 'HAROLD',
//   44: 'HARRY',
//   45: 'HARVEY',
//   46: 'HENRY',
//   47: 'HERBERT',
//   48: 'HERMAN',
//   49: 'HOMER',
//   50: 'HOWARD',
//   51: 'JACK',
//   52: 'JAMES',
//   53: 'JESSE',
//   54: 'JOE',
//   55: 'JOHN',
//   56: 'JOSEPH',
//   57: 'KENNETH',
//   58: 'LAWRENCE',
//   59: 'LEE',
//   60: 'LEO',
//   61: 'LEON',
//   62: 'LEONARD',
//   63: 'LEROY',
//   64: 'LESTER',
//   65: 'LEWIS',
//   66: 'LLOYD',
//   67: 'LOUIS',
//   68: 'MARTIN',
//   69: 'MARVIN',
//   70: 'MELVIN',
//   71: 'MICHAEL',
//   72: 'MILTON',
//   73: 'NORMAN',
//   74: 'OSCAR',
//   75: 'PAUL',
//   78: 'PETER',
//   76: 'PHILIP',
//   77: 'RALPH',
//   83: 'RAY',
//   79: 'RAYMOND',
//   80: 'RICHARD',
//   81: 'ROBERT',
//   82: 'ROGER',
//   84: 'RONALD',
//   85: 'ROY',
//   86: 'RUSSELL',
//   87: 'SAM',
//   88: 'SAMUEL',
//   89: 'STANLEY',
//   90: 'THEODORE',
//   91: 'THOMAS',
//   92: 'VERNON',
//   93: 'VICTOR',
//   94: 'VINCENT', 
//   95: 'WALLACE',
//   96: 'WALTER',
//   97: 'WARREN',
//   98: 'WAYNE',
//   99: 'WILLARD',
//   100: 'WILLIAM',  // 100 total
// }

// last_names = {
//   1:,"ADAMS", 
//   2:, 'ALLEN',
//   3:, 'ANDERSON',
//   4:, 'BAILEY',
//   5:, 'BAKER',
//   6:, 'BARNES',
//   7:, 'BELL',
//   8:,'BENNETT',
//   9:, 'BOYD',
//   10:, 'BROOKS',
//   11:, 'BROWN',
//   12:, 'BRYANT',
//   13:, 'BUTLER',
//   14:, 'CAMPBELL', 
//   15:, 'CARPENTER', 
//   16:, 'CARTER',
//   17:, 'CLARK',
//   18:, 'COLEMAN',
//   19:, 'COLLINS',
//   20:, 'COOK',
//   21:, 'COOPER',
//   22:, 'COX', 
//   23:, 'DAVIS',
//   24:, 'DIXON',
//   25:, 'DONALDSON',
//   26:, 'EDWARDS',
//   27:, 'ELLIS',
//   28:, 'EVANS',
//   29:, 'FOSTER',
//   30:, 'GARCIA',
//   31:, 'GRAY',
//   32:, 'GREEN',
//   33:, 'GRIFFIN',
//   34:, 'HALL',
//   35:, 'HARRIS',
//   36:, 'HAYES',
//   37:, 'HILL',
//   38:, 'HOWARD',
//   39:, 'HUDSON',
//   40:, 'HUGHES',
//   41:, 'HUNTER',
//   42:, 'JACKSON',
//   43:, 'JAMES',
//   44:, 'JENKINS',
//   45:, 'JOHNSON',
//   46:, 'JONES',
//   47:, 'KELLY',
//   48:, 'KENNEDY',
//   49:, 'KERESEY',
//   50:, 'LEE',
//   51:, 'LEWIS',
//   52:, 'LONG',
//   53:, 'MARTIN',
//   54:, 'MASON',
//   55:, 'MILLER',
//   56:, 'MITCHELL',
//   57:, 'MOORE',
//   58:, 'MORGAN',
//   59:, 'MORETTI',
//   60:, 'MURPHY',
//   61:, 'NELSON',
//   62:, 'PARKER',
//   63:, 'PALMER',
//   64:, 'PATTERSON',
//   65:, 'PERRY',
//   66:, 'PETERSON',
//   67:, 'PHILLIPS',
//   68:, 'PIERCE',
//   69:, 'PORTER',
//   70:, 'POWELL',
//   71:, 'PRICE',
//   72:, 'REED',
//   73:, 'RICHARDSON',
//   74:, 'ROBERTS',
//   75:, 'ROBINSON',
//   78:, 'ROSS',
//   76:, 'ROGERS',
//   77:, 'RODRIGUEZ',
//   83:, 'SMITH',
//   79:, 'RUSSO',
//   80:, 'SANDERS',
//   81:, 'SCOTT',
//   82:, 'SIMMONS',
//   84:, 'SPENCER',
//   85:, 'STEVENS',
//   86:, 'STEWART',
//   87:, 'TAYLOR',
//   88:, 'THOMAS',
//   89:, 'THOMPSON',
//   90:, 'TURNER',
//   91:, 'WALKER',
//   92:, 'WARD',
//   93:, 'WASHINGTON',
//   94:, 'WATSON', 
//   95:, 'WHITE',
//   96:, 'WILLIAMS',
//   97:, 'WILSON',
//   98:, 'WOOD',
//   99:, 'WRIGHT',
//   100:, 'YOUNG',  #100 total
// }




















